name: Deploy to Production

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/alem/core
            echo "Pulling latest code..."
            git pull origin master

            echo "Installing composer deps..."
            composer install --no-dev --optimize-autoloader

            echo "Running migrations..."
            php artisan migrate --force

            echo "Clearing caches..."
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Restarting services..."
            systemctl reload nginx
            systemctl restart php8.3-fpm

            echo "Deployment complete!"
